[package]
edition = "2021"
name = "forgic"
version = "0.1.0"

[dependencies]
libic = {version = "0.1.0", path = "../libic"}
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
xmltojson = "0"
